//Generated by TurboLink CodeGenerator, do not edit!
#include "EnableGrpcIncludes.h"
#include "SGreet/GreetService.h"
#include "SGreet/GreetClient.h"
#include "GreetService_Private.h"
#include "GreetMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UGreeter::UGreeter()
	: d(new UGreeter::Private())
{
}

UGreeter::~UGreeter()
{
	delete d;
}

void UGreeter::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("Greeter"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to Greeter: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel(TCHAR_TO_UTF8(*serviceEndPoint), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = greet::Greeter::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UGreeter::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UGreeterClient* UGreeter::MakeClient()
{
	auto client = UGrpcService::MakeClient<UGreeterClient>();
	return client;
}

void UGreeter::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UGreeter::CallSayHello(const FGrpcGreetHelloRequest& Request, FSayHelloResponseLambda ResponseLambda)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UGreeterSayHelloLambdaWrapper* lambdaWrapper = NewObject<UGreeterSayHelloLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitSayHello();
	InnerClient->OnSayHelloResponse.AddUniqueDynamic(lambdaWrapper, &UGreeterSayHelloLambdaWrapper::OnResponse);
	InnerClient->SayHello(lambdaWrapper->Handle, Request);
}
