//Generated by TurboLink CodeGenerator, do not edit!
#include "EnableGrpcIncludes.h"
#include "SGreet/GreetMessage.h"
#include "SGreet/GreetMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcGreetHelloRequest, ::greet::HelloRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGreetHelloReply, ::greet::HelloReply)

