//Generated by TurboLink CodeGenerator, do not edit!
#include "EnableGrpcIncludes.h"
#include "GreetMarshaling.h"

void GRPC_TO_TURBOLINK(const ::greet::HelloRequest* in, FGrpcGreetHelloRequest* out)
{
    out->Name=UTF8_TO_TCHAR(in->name().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcGreetHelloRequest* in, ::greet::HelloRequest* out)
{
    out->set_name(TCHAR_TO_UTF8(*(in->Name)));
}

void GRPC_TO_TURBOLINK(const ::greet::HelloReply* in, FGrpcGreetHelloReply* out)
{
    out->Message=UTF8_TO_TCHAR(in->message().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcGreetHelloReply* in, ::greet::HelloReply* out)
{
    out->set_message(TCHAR_TO_UTF8(*(in->Message)));
}

