//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SGreet/GreetMessage.h"
#include "SGreet/GreetMarshaling.h"
class GrpcContext_Greeter_SayHello : public GrpcContext_Ping_Pong<Greeter_SayHello_ReaderWriter, ::greet::HelloReply>
{
	friend class UGreeterClient;
	typedef GrpcContext_Ping_Pong<Greeter_SayHello_ReaderWriter, ::greet::HelloReply> Super;

private:
	void Call(const FGrpcGreetHelloRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_Greeter_SayHello(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

