//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SGreet/GreetClient.h"
#include "GreetService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UGreeter : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UGreeterClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UGreeterClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGreetHelloReply& Response)> FSayHelloResponseLambda;
	void CallSayHello(const FGrpcGreetHelloRequest& Request, FSayHelloResponseLambda ResponseLambda);

public:
	class Private;
	Private* const d = nullptr;

public:
	UGreeter();
	virtual ~UGreeter();
};

