# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY *.csproj ./RPCService
WORKDIR /source/RPCService
RUN dotnet restore

# copy everything else and build app
COPY . ./RPCService/
WORKDIR /source/RPCService
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
# Copyy from build stage
COPY --from=build /app ./
# Expose gRPC port
EXPOSE 5249
ENTRYPOINT ["dotnet", "RPCService.dll"]


